(function(){
 const D=window.MiraeData, client=D.client, configured=D.configured; let cat='notice';
 const $=id=>document.getElementById(id); const loginBox=$('loginBox'), workspace=$('workspace');
 const modeBox=$('modeBox'), rows=$('rows'), status=$('saveStatus');
 function localAll(){return D.localAll()}
 function saveLocal(arr){localStorage.setItem('mirae_posts',JSON.stringify(arr))}
 function modeText(){modeBox.innerHTML=configured?'<strong>온라인 관리 모드</strong>Supabase에 저장되어 PC와 휴대폰에서 동일하게 반영됩니다.':'<strong>테스트 모드</strong>아직 Supabase가 연결되지 않아 이 브라우저에만 저장됩니다. 실제 운영 전 README의 연결 절차를 완료하세요.'}
 async function authInit(){modeText(); if(!configured){$('loginHint').textContent='Supabase 연결 전 테스트 모드입니다. 이메일/비밀번호 없이 로그인 버튼을 누르세요.'; return}
   const {data}=await client.auth.getSession(); if(data.session) showWorkspace(); }
 async function login(){ $('loginStatus').textContent=''; if(!configured){showWorkspace();return} const {error}=await client.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value}); if(error){$('loginStatus').textContent='로그인 실패: '+error.message;return} showWorkspace();}
 async function logout(){if(configured)await client.auth.signOut();workspace.style.display='none';loginBox.style.display='block'}
 function showWorkspace(){loginBox.style.display='none';workspace.style.display='block';reset();loadRows()}
 async function getAdminPosts(){ if(configured){const {data,error}=await client.from('posts').select('*').eq('category',cat).order('created_at',{ascending:false}); if(error){status.textContent='목록 불러오기 실패: '+error.message;return[]}return data||[]} return localAll().filter(x=>x.category===cat).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)); }
 async function loadRows(){ $('listTitle').textContent=cat==='notice'?'공지사항 목록':'자료실 목록'; rows.innerHTML='<div class="status">불러오는 중...</div>';const data=await getAdminPosts(); rows.innerHTML=data.length?data.map(p=>`<div class="row"><div><div class="title">${D.escapeHtml(p.title)}</div><div class="date">${D.formatDate(p.created_at)} · ${p.published===false?'비공개':'공개'}</div></div><div>${p.file_url?'<span style="font-size:12px;color:#0d63c9">첨부 있음</span>':''}</div><div class="row-actions"><button class="edit" data-edit="${p.id}">수정</button><button class="del" data-del="${p.id}">삭제</button></div></div>`).join(''):'<div class="status">등록된 글이 없습니다.</div>'; rows.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editPost(b.dataset.edit)); rows.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deletePost(b.dataset.del)); }
 async function findPost(id){const data=await getAdminPosts();return data.find(x=>String(x.id)===String(id))}
 async function editPost(id){const p=await findPost(id);if(!p)return;$('editId').value=p.id;$('title').value=p.title||'';$('body').value=p.content||'';$('published').checked=p.published!==false;$('fileNote').textContent=p.file_url?'현재 첨부파일이 있습니다. 새 파일을 선택하면 교체됩니다.':'필요한 경우 파일을 첨부할 수 있습니다.';$('saveBtn').textContent='수정 저장';window.scrollTo({top:0,behavior:'smooth'})}
 function reset(){$('editId').value='';$('title').value='';$('body').value='';$('file').value='';$('published').checked=true;$('fileNote').textContent='필요한 경우 PDF, 한글, 엑셀 등 파일을 첨부할 수 있습니다.';$('saveBtn').textContent='등록하기';status.textContent=''}
 async function uploadFile(file){if(!file)return null; if(!configured)return null; const safe=(Date.now()+'-'+file.name).replace(/[^a-zA-Z0-9._가-힣-]/g,'_');const path=`${cat}/${safe}`;const {error}=await client.storage.from('attachments').upload(path,file,{upsert:false});if(error)throw error;const {data}=client.storage.from('attachments').getPublicUrl(path);return data.publicUrl}
 async function save(){const title=$('title').value.trim(),body=$('body').value.trim(); if(!title){status.textContent='제목을 입력하세요.';return} status.textContent='저장 중...';const id=$('editId').value;try{let fileUrl=null;const f=$('file').files[0];if(f)fileUrl=await uploadFile(f); if(configured){let payload={category:cat,title,content:body,published:$('published').checked,updated_at:new Date().toISOString()};if(fileUrl)payload.file_url=fileUrl;let q=id?client.from('posts').update(payload).eq('id',id):client.from('posts').insert(payload);const {error}=await q;if(error)throw error;}else{let arr=localAll(); if(id){arr=arr.map(p=>String(p.id)===String(id)?{...p,title,content:body,published:$('published').checked,updated_at:new Date().toISOString()}:p)}else{arr.push({id:'local-'+Date.now(),category:cat,title,content:body,published:$('published').checked,file_url:null,created_at:new Date().toISOString(),updated_at:new Date().toISOString()})}saveLocal(arr)}status.textContent='저장되었습니다.';reset();await loadRows()}catch(e){status.textContent='저장 실패: '+e.message}}
 async function deletePost(id){if(!confirm('이 글을 삭제할까요?'))return; if(configured){const {error}=await client.from('posts').delete().eq('id',id);if(error){status.textContent='삭제 실패: '+error.message;return}}else{saveLocal(localAll().filter(p=>String(p.id)!==String(id)))}reset();loadRows()}
 document.querySelectorAll('.tab[data-cat]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab[data-cat]').forEach(x=>x.classList.remove('active'));b.classList.add('active');cat=b.dataset.cat;reset();loadRows()});
 $('loginBtn').onclick=login;$('logoutBtn').onclick=logout;$('saveBtn').onclick=save;$('resetBtn').onclick=reset; authInit();
})();
